services:
  python-ml:
    build: .
    container_name: python-ml
    working_dir: /opt/project/PythonProjects
    volumes:
      - C:/Users/esdra/PycharmProjects/PythonProject/src:/opt/project/PythonProjects/src
      - C:/Users/esdra/PycharmProjects/PythonProject/IrisTrainerMain.py:/opt/project/PythonProjects/IrisTrainerMain.py
      - report_data:/opt/project/report
      - models_data:/opt/project/models
    tty: true
    stdin_open: true

volumes:
  report_data:
  models_data:
